import { resolveProductImages } from './imageHelpers.js';

/**
 * ShopHub product catalog
 *
 * PRICING: Realistic INR retail prices (Amazon India–style, always with paise).
 * IMAGES: 3–5 verified Pexels stock photos per product (800×800 crop).
 *         item to swap in files from client/public/assets/products/{slug}/
 *
 * Fields:
 *   slug          — folder name for custom images
 *   useLocalImages — set true to use /assets/products/{slug}/1.jpg …
 *   images        — auto-built from Unsplash or local paths
 *   price         — current sale price (INR)
 *   originalPrice — MRP / list price for strikethrough (optional)
 */

const catalog = [
  // ─── Electronics ───────────────────────────────────────────────────────────
  {
    slug: 'probook-gaming-laptop',
    title: 'ProBook Gaming Laptop 15.6"',
    description:
      'High-performance gaming laptop with RTX 4060, 16GB RAM, 512GB SSD. 144Hz display, dual-fan cooling. Perfect for gaming and content creation.',
    price: 89999.0,
    originalPrice: 109999.0,
    brand: 'TechPro',
    category: 'Electronics',
    images: resolveProductImages('probook-gaming-laptop', [346885, 442574, 2040340, 3205733]),
    rating: 4.5,
    reviewCount: 1284,
    stock: 45,
    badges: ['Best Seller', 'Prime'],
    tags: ['laptop', 'gaming', 'computer'],
    featured: 'deals',
  },
  {
    slug: 'ultraslim-notebook-14',
    title: 'UltraSlim Notebook 14"',
    description:
      'Lightweight ultrabook with Intel Core i7, 16GB RAM, 512GB SSD. 14" FHD display, all-day battery. Perfect for work and travel.',
    price: 74999.0,
    originalPrice: 84999.0,
    brand: 'TechPro',
    category: 'Electronics',
    images: resolveProductImages('ultraslim-notebook-14', [442574, 346885, 2040340, 133298]),
    rating: 4.3,
    reviewCount: 892,
    stock: 60,
    badges: ['Prime'],
    tags: ['laptop', 'ultrabook', 'work'],
    featured: 'recommended',
  },
  {
    slug: 'budget-chromebook-11',
    title: 'Budget Chromebook 11.6"',
    description:
      'Affordable Chromebook for students. 4GB RAM, 64GB storage, 11.6" HD display. Lightweight and long battery life.',
    price: 24999.0,
    originalPrice: 29999.0,
    brand: 'WebBook',
    category: 'Electronics',
    images: resolveProductImages('budget-chromebook-11', [2040340, 442574, 346885, 3205733]),
    rating: 4.0,
    reviewCount: 456,
    stock: 100,
    badges: ['Prime'],
    tags: ['laptop', 'chromebook', 'budget'],
    featured: 'deals',
  },
  {
    slug: 'wireless-noise-cancelling-headphones',
    title: 'Wireless Noise-Cancelling Headphones',
    description:
      'Premium over-ear headphones with 30-hour battery, active noise cancellation, and hi-res audio support.',
    price: 4999.0,
    originalPrice: 7999.0,
    brand: 'SoundMax',
    category: 'Electronics',
    images: resolveProductImages('wireless-noise-cancelling-headphones', [3394650, 1649771, 3780681, 393047]),
    rating: 4.6,
    reviewCount: 3421,
    stock: 200,
    badges: ['Best Seller', 'Prime'],
    tags: ['headphones', 'audio', 'wireless'],
    featured: 'bestseller',
  },
  {
    slug: 'smartwatch-pro-series-7',
    title: 'Smart Watch Pro Series 7',
    description:
      'Advanced fitness tracking, heart rate & SpO2 monitor, built-in GPS, 5-day battery. Water resistant to 50m.',
    price: 12999.0,
    originalPrice: 15999.0,
    brand: 'FitTech',
    category: 'Electronics',
    images: resolveProductImages('smartwatch-pro-series-7', [437037, 393047, 267390, 267391]),
    rating: 4.4,
    reviewCount: 2103,
    stock: 75,
    badges: ['Prime'],
    tags: ['watch', 'fitness', 'smartwatch'],
    featured: 'recommended',
  },
  {
    slug: '4k-smart-tv-55',
    title: '4K Ultra HD Smart TV 55"',
    description:
      'Stunning 4K UHD display with HDR10+, Dolby Audio, built-in streaming apps, and voice control remote.',
    price: 42999.0,
    originalPrice: 54999.0,
    brand: 'ViewMax',
    category: 'Electronics',
    images: resolveProductImages('4k-smart-tv-55', [1571458, 1201990, 5721908, 346885]),
    rating: 4.7,
    reviewCount: 1876,
    stock: 30,
    badges: ['Best Seller', 'Prime'],
    tags: ['tv', 'television', '4k'],
    featured: 'deals',
  },
  {
    slug: 'wireless-bluetooth-earbuds',
    title: 'Wireless Bluetooth Earbuds',
    description:
      'True wireless earbuds with charging case, ENC microphones, IPX5 water resistance. 24-hour total playtime.',
    price: 1999.0,
    originalPrice: 2999.0,
    brand: 'SoundMax',
    category: 'Electronics',
    images: resolveProductImages('wireless-bluetooth-earbuds', [3780681, 393047, 3394650, 1649771]),
    rating: 4.2,
    reviewCount: 5678,
    stock: 300,
    badges: ['Best Seller', 'Prime'],
    tags: ['earbuds', 'audio', 'wireless'],
    featured: 'bestseller',
  },
  {
    slug: 'mechanical-gaming-keyboard',
    title: 'Mechanical Gaming Keyboard RGB',
    description:
      'Cherry MX Red switches, per-key RGB lighting, programmable macros, aluminium frame, USB-C detachable cable.',
    price: 3499.0,
    originalPrice: 4499.0,
    brand: 'GameGear',
    category: 'Electronics',
    images: resolveProductImages('mechanical-gaming-keyboard', [2115257, 1148820, 2539651, 346885]),
    rating: 4.5,
    reviewCount: 934,
    stock: 80,
    badges: ['Prime'],
    tags: ['keyboard', 'gaming', 'mechanical'],
    featured: 'recommended',
  },
  {
    slug: 'portable-bluetooth-speaker',
    title: 'Portable Bluetooth Speaker',
    description:
      '360° sound, 12-hour battery, IPX7 waterproof. Perfect for outdoor parties, travel, and poolside listening.',
    price: 2499.0,
    originalPrice: 3499.0,
    brand: 'SoundMax',
    category: 'Electronics',
    images: resolveProductImages('portable-bluetooth-speaker', [3761509, 1305668, 1305669, 3394650]),
    rating: 4.3,
    reviewCount: 2341,
    stock: 150,
    badges: ['Prime'],
    tags: ['speaker', 'bluetooth', 'portable'],
    featured: 'deals',
  },
  {
    slug: 'tablet-10-wifi',
    title: 'Tablet 10.1" WiFi 64GB',
    description:
      'Vivid 10.1" IPS display, quad speakers, 64GB storage, 8-hour battery. Ideal for reading, streaming, and browsing.',
    price: 18999.0,
    originalPrice: 22999.0,
    brand: 'TabTech',
    category: 'Electronics',
    images: resolveProductImages('tablet-10-wifi', [133298, 3205733, 442574, 2040340]),
    rating: 4.1,
    reviewCount: 678,
    stock: 90,
    badges: ['Prime'],
    tags: ['tablet', 'ipad', 'reading'],
    featured: 'recommended',
  },

  // ─── Books ─────────────────────────────────────────────────────────────────
  {
    slug: 'art-of-programming',
    title: 'The Art of Programming',
    description:
      'Comprehensive guide to modern software development, design patterns, clean code, and system architecture.',
    price: 599.0,
    originalPrice: 799.0,
    brand: 'TechPress',
    category: 'Books',
    images: resolveProductImages('art-of-programming', [261102, 256450, 261895, 261909]),
    rating: 4.8,
    reviewCount: 4521,
    stock: 200,
    badges: ['Best Seller', 'Prime'],
    tags: ['programming', 'software', 'tech'],
    featured: 'bestseller',
  },
  {
    slug: 'mindful-living-guide',
    title: 'Mindful Living: A Daily Guide',
    description:
      'Transform your life with practical mindfulness techniques, guided meditations, and daily reflection exercises.',
    price: 349.0,
    originalPrice: 499.0,
    brand: 'WellnessPub',
    category: 'Books',
    images: resolveProductImages('mindful-living-guide', [256450, 261102, 261895, 261909]),
    rating: 4.6,
    reviewCount: 3210,
    stock: 150,
    badges: ['Prime'],
    tags: ['self-help', 'mindfulness', 'wellness'],
    featured: 'recommended',
  },
  {
    slug: 'world-history-chronicle',
    title: 'World History: A Complete Chronicle',
    description:
      'From ancient civilizations to the modern era — an engaging, illustrated journey through world history.',
    price: 499.0,
    originalPrice: 699.0,
    brand: 'HistoryHouse',
    category: 'Books',
    images: resolveProductImages('world-history-chronicle', [261909, 256450, 261895, 261102]),
    rating: 4.5,
    reviewCount: 1890,
    stock: 100,
    badges: ['Prime'],
    tags: ['history', 'non-fiction', 'education'],
    featured: 'deals',
  },
  {
    slug: 'midnight-garden-novel',
    title: 'The Midnight Garden - Fiction Novel',
    description:
      'A captivating tale of mystery, love, and secrets set in a Victorian-era garden. Perfect for fans of literary fiction.',
    price: 299.0,
    originalPrice: 449.0,
    brand: 'StoryLine',
    category: 'Books',
    images: resolveProductImages('midnight-garden-novel', [261102, 261909, 256450, 261895]),
    rating: 4.7,
    reviewCount: 5670,
    stock: 300,
    badges: ['Best Seller', 'Prime'],
    tags: ['fiction', 'novel', 'mystery'],
    featured: 'bestseller',
  },
  {
    slug: 'cook-like-a-chef',
    title: 'Cook Like a Chef: 500 Recipes',
    description:
      'Professional recipes made simple. 500 tested recipes from appetizers to desserts, with step-by-step photos.',
    price: 699.0,
    originalPrice: 899.0,
    brand: 'CulinaryArts',
    category: 'Books',
    images: resolveProductImages('cook-like-a-chef', [4226766, 261895, 256450, 2396220]),
    rating: 4.4,
    reviewCount: 2340,
    stock: 120,
    badges: ['Prime'],
    tags: ['cooking', 'recipes', 'food'],
    featured: 'recommended',
  },
  {
    slug: 'financial-freedom-blueprint',
    title: 'Financial Freedom Blueprint',
    description:
      'Build wealth, invest wisely, and achieve financial independence. Covers stocks, mutual funds, and retirement planning.',
    price: 399.0,
    originalPrice: 549.0,
    brand: 'MoneyWise',
    category: 'Books',
    images: resolveProductImages('financial-freedom-blueprint', [590041, 590042, 590043, 590044]),
    rating: 4.3,
    reviewCount: 1567,
    stock: 180,
    badges: ['Prime'],
    tags: ['finance', 'investing', 'money'],
    featured: 'deals',
  },
  {
    slug: 'lost-kingdom-children',
    title: "Children's Adventure: The Lost Kingdom",
    description:
      'An exciting adventure story for young readers ages 8–12. Illustrated chapter book with positive themes.',
    price: 249.0,
    originalPrice: 349.0,
    brand: 'KidsRead',
    category: 'Books',
    images: resolveProductImages('lost-kingdom-children', [861308, 861309, 861310, 861311]),
    rating: 4.9,
    reviewCount: 890,
    stock: 250,
    badges: ['Best Seller', 'Prime'],
    tags: ['children', 'adventure', 'kids'],
    featured: 'recommended',
  },
  {
    slug: 'science-physics-everyone',
    title: 'Science Explained: Physics for Everyone',
    description:
      'Complex physics concepts made accessible and fun. Covers mechanics, thermodynamics, and quantum basics.',
    price: 449.0,
    originalPrice: 599.0,
    brand: 'SciPub',
    category: 'Books',
    images: resolveProductImages('science-physics-everyone', [261909, 261895, 256450, 261102]),
    rating: 4.5,
    reviewCount: 678,
    stock: 90,
    badges: ['Prime'],
    tags: ['science', 'physics', 'education'],
    featured: 'recommended',
  },

  // ─── Home & Kitchen ────────────────────────────────────────────────────────
  {
    slug: 'stainless-cookware-10pc',
    title: 'Stainless Steel Cookware Set 10-Piece',
    description:
      'Professional-grade tri-ply stainless steel pots and pans. Even heat distribution, oven-safe to 260°C.',
    price: 4999.0,
    originalPrice: 6999.0,
    brand: 'ChefMaster',
    category: 'Home & Kitchen',
    images: resolveProductImages('stainless-cookware-10pc', [4226766, 4226769, 4226770, 2396220]),
    rating: 4.6,
    reviewCount: 3456,
    stock: 60,
    badges: ['Best Seller', 'Prime'],
    tags: ['cookware', 'kitchen', 'cooking'],
    featured: 'deals',
  },
  {
    slug: 'robot-vacuum-mapping',
    title: 'Robot Vacuum Cleaner with Mapping',
    description:
      'LiDAR navigation, app control, auto-empty base, 3000Pa suction. Works on hardwood, tile, and carpet.',
    price: 24999.0,
    originalPrice: 31999.0,
    brand: 'CleanBot',
    category: 'Home & Kitchen',
    images: resolveProductImages('robot-vacuum-mapping', [4107281, 4107280, 4107282, 4107283]),
    rating: 4.4,
    reviewCount: 2134,
    stock: 40,
    badges: ['Prime'],
    tags: ['vacuum', 'cleaning', 'smart home'],
    featured: 'recommended',
  },
  {
    slug: 'memory-foam-pillow-2pk',
    title: 'Memory Foam Pillow Set of 2',
    description:
      'Cooling gel-infused memory foam pillows with removable bamboo cover. Optimal neck support for all sleep positions.',
    price: 1999.0,
    originalPrice: 2799.0,
    brand: 'SleepWell',
    category: 'Home & Kitchen',
    images: resolveProductImages('memory-foam-pillow-2pk', [1325859, 1454805, 1454806]),
    rating: 4.5,
    reviewCount: 4567,
    stock: 200,
    badges: ['Best Seller', 'Prime'],
    tags: ['pillow', 'bedding', 'sleep'],
    featured: 'bestseller',
  },
  {
    slug: 'coffee-maker-12cup',
    title: 'Programmable Coffee Maker 12-Cup',
    description:
      'Programmable timer, thermal carafe keeps coffee hot for 4 hours, auto shut-off, reusable filter included.',
    price: 3499.0,
    originalPrice: 4499.0,
    brand: 'BrewMaster',
    category: 'Home & Kitchen',
    images: resolveProductImages('coffee-maker-12cup', [2396220, 302899, 302900, 302901]),
    rating: 4.3,
    reviewCount: 1890,
    stock: 85,
    badges: ['Prime'],
    tags: ['coffee', 'kitchen', 'appliance'],
    featured: 'deals',
  },
  {
    slug: 'air-purifier-hepa',
    title: 'Air Purifier HEPA Filter Large Room',
    description:
      'True HEPA H13 filter removes 99.97% of allergens, dust, and odours. Covers up to 500 sq ft, whisper-quiet sleep mode.',
    price: 8999.0,
    originalPrice: 11999.0,
    brand: 'PureAir',
    category: 'Home & Kitchen',
    images: resolveProductImages('air-purifier-hepa', [4107282, 4107283, 4107284, 4107281]),
    rating: 4.6,
    reviewCount: 1234,
    stock: 55,
    badges: ['Prime'],
    tags: ['air purifier', 'health', 'home'],
    featured: 'recommended',
  },
  {
    slug: 'baking-sheet-3pc',
    title: 'Non-Stick Baking Sheet Set 3-Piece',
    description:
      'Heavy-duty aluminium baking sheets with non-stick coating. Dishwasher safe, includes small, medium, and large pans.',
    price: 899.0,
    originalPrice: 1299.0,
    brand: 'BakePro',
    category: 'Home & Kitchen',
    images: resolveProductImages('baking-sheet-3pc', [4226766, 4226769, 4226770]),
    rating: 4.4,
    reviewCount: 987,
    stock: 150,
    badges: ['Prime'],
    tags: ['baking', 'kitchen', 'cookware'],
    featured: 'recommended',
  },
  {
    slug: 'smart-led-bulbs-4pk',
    title: 'Smart LED Light Bulbs 4-Pack',
    description:
      'WiFi-enabled RGB bulbs, 16 million colours, voice control via Alexa/Google. 9W (60W equivalent), E27 base.',
    price: 1499.0,
    originalPrice: 1999.0,
    brand: 'BrightHome',
    category: 'Home & Kitchen',
    images: resolveProductImages('smart-led-bulbs-4pk', [929496, 929497, 3100827, 3100828]),
    rating: 4.2,
    reviewCount: 2345,
    stock: 180,
    badges: ['Prime'],
    tags: ['smart home', 'lighting', 'led'],
    featured: 'deals',
  },
  {
    slug: 'egyptian-cotton-sheets',
    title: 'Egyptian Cotton Sheet Set Queen',
    description:
      '800 thread count Egyptian cotton, ultra-soft and breathable. Includes fitted sheet, flat sheet, and 2 pillowcases.',
    price: 3999.0,
    originalPrice: 5499.0,
    brand: 'LuxBedding',
    category: 'Home & Kitchen',
    images: resolveProductImages('egyptian-cotton-sheets', [1325859, 1454805, 1454806]),
    rating: 4.7,
    reviewCount: 1567,
    stock: 70,
    badges: ['Best Seller', 'Prime'],
    tags: ['bedding', 'sheets', 'cotton'],
    featured: 'bestseller',
  },
  {
    slug: 'blender-high-speed-1500w',
    title: 'Blender High-Speed 1500W',
    description:
      '1500W motor crushes ice in seconds. Make smoothies, soups, nut butters, and baby food. BPA-free Tritan jar.',
    price: 4499.0,
    originalPrice: 5999.0,
    brand: 'BlendPro',
    category: 'Home & Kitchen',
    images: resolveProductImages('blender-high-speed-1500w', [4226766, 4226769, 302899, 2396220]),
    rating: 4.5,
    reviewCount: 2100,
    stock: 65,
    badges: ['Prime'],
    tags: ['blender', 'kitchen', 'appliance'],
    featured: 'recommended',
  },

  // ─── Fashion ───────────────────────────────────────────────────────────────
  {
    slug: 'classic-fit-denim-jeans',
    title: 'Classic Fit Denim Jeans',
    description:
      'Comfortable stretch denim with classic five-pocket styling. Mid-rise, straight leg. Machine washable.',
    price: 1999.0,
    originalPrice: 2999.0,
    brand: 'DenimCo',
    category: 'Fashion',
    images: resolveProductImages('classic-fit-denim-jeans', [1598507, 1598508, 1598505]),
    rating: 4.3,
    reviewCount: 4567,
    stock: 200,
    badges: ['Best Seller', 'Prime'],
    tags: ['jeans', 'denim', 'pants'],
    featured: 'deals',
  },
  {
    slug: 'cotton-crew-tshirt-3pk',
    title: 'Cotton Crew Neck T-Shirt 3-Pack',
    description:
      '100% premium combed cotton tees in black, white, and navy. Pre-shrunk, tagless comfort collar.',
    price: 1299.0,
    originalPrice: 1799.0,
    brand: 'BasicWear',
    category: 'Fashion',
    images: resolveProductImages('cotton-crew-tshirt-3pk', [428338, 428340, 997909, 997910]),
    rating: 4.5,
    reviewCount: 8901,
    stock: 500,
    badges: ['Best Seller', 'Prime'],
    tags: ['tshirt', 'cotton', 'basics'],
    featured: 'bestseller',
  },
  {
    slug: 'waterproof-hiking-boots',
    title: 'Waterproof Hiking Boots',
    description:
      'Full-grain leather upper, Vibram rubber sole, waterproof membrane. Ideal for trails and all-terrain hiking.',
    price: 5999.0,
    originalPrice: 7999.0,
    brand: 'TrailMax',
    category: 'Fashion',
    images: resolveProductImages('waterproof-hiking-boots', [1032110, 1032111, 1032112]),
    rating: 4.6,
    reviewCount: 1234,
    stock: 80,
    badges: ['Prime'],
    tags: ['boots', 'hiking', 'outdoor'],
    featured: 'recommended',
  },
  {
    slug: 'leather-crossbody-bag',
    title: 'Leather Crossbody Bag',
    description:
      'Genuine leather crossbody with adjustable strap, zip closure, and multiple interior compartments.',
    price: 3499.0,
    originalPrice: 4999.0,
    brand: 'LuxeBag',
    category: 'Fashion',
    images: resolveProductImages('leather-crossbody-bag', [1152077, 1152070, 1152069, 1152068]),
    rating: 4.4,
    reviewCount: 2345,
    stock: 120,
    badges: ['Prime'],
    tags: ['bag', 'handbag', 'leather'],
    featured: 'deals',
  },
  {
    slug: 'running-shoes-lightweight',
    title: 'Running Shoes Lightweight',
    description:
      'Breathable mesh upper, responsive foam midsole, rubber outsole. Designed for daily road running and gym.',
    price: 3999.0,
    originalPrice: 5499.0,
    brand: 'RunFast',
    category: 'Fashion',
    images: resolveProductImages('running-shoes-lightweight', [190483, 190484, 190485]),
    rating: 4.5,
    reviewCount: 5678,
    stock: 150,
    badges: ['Best Seller', 'Prime'],
    tags: ['shoes', 'running', 'sneakers'],
    featured: 'bestseller',
  },
  {
    slug: 'wool-blend-winter-coat',
    title: 'Wool Blend Winter Coat',
    description:
      'Warm wool-blend mid-length coat with removable hood, button closure, and side pockets. Lined for extra warmth.',
    price: 7999.0,
    originalPrice: 10999.0,
    brand: 'WarmWear',
    category: 'Fashion',
    images: resolveProductImages('wool-blend-winter-coat', [1926769, 768767, 6311654, 6311655]),
    rating: 4.3,
    reviewCount: 890,
    stock: 45,
    badges: ['Prime'],
    tags: ['coat', 'winter', 'outerwear'],
    featured: 'deals',
  },
  {
    slug: 'polarized-sunglasses-uv400',
    title: 'Polarized Sunglasses UV400',
    description:
      'Classic aviator polarized lenses with full UV400 protection. Lightweight metal frame with nose pads.',
    price: 1499.0,
    originalPrice: 2199.0,
    brand: 'SunStyle',
    category: 'Fashion',
    images: resolveProductImages('polarized-sunglasses-uv400', [701877, 46710, 1365425, 1308881]),
    rating: 4.2,
    reviewCount: 3456,
    stock: 250,
    badges: ['Prime'],
    tags: ['sunglasses', 'accessories', 'summer'],
    featured: 'recommended',
  },
  {
    slug: 'silk-scarf-floral',
    title: 'Silk Scarf Floral Print',
    description:
      '100% mulberry silk scarf with elegant floral print. 90×90 cm, hand-rolled edges. Gift box included.',
    price: 2199.0,
    originalPrice: 2999.0,
    brand: 'LuxeBag',
    category: 'Fashion',
    images: resolveProductImages('silk-scarf-floral', [994517, 994518, 994519, 994520]),
    rating: 4.6,
    reviewCount: 567,
    stock: 100,
    badges: ['Prime'],
    tags: ['scarf', 'silk', 'accessories'],
    featured: 'recommended',
  },
  {
    slug: 'athletic-joggers-pockets',
    title: 'Athletic Joggers with Pockets',
    description:
      'Moisture-wicking polyester blend, tapered fit, zip pockets. Perfect for gym, running, or casual wear.',
    price: 1799.0,
    originalPrice: 2499.0,
    brand: 'ActiveFit',
    category: 'Fashion',
    images: resolveProductImages('athletic-joggers-pockets', [997909, 997910, 997911, 997912]),
    rating: 4.4,
    reviewCount: 2100,
    stock: 180,
    badges: ['Prime'],
    tags: ['joggers', 'athletic', 'pants'],
    featured: 'recommended',
  },
];

export default catalog;
